# Generated by Django 2.1.2 on 2018-11-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, unique=True)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '字段',
                'verbose_name_plural': '字段',
            },
        ),
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100, unique=True)),
                ('flag', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '表单',
                'verbose_name_plural': '表单',
            },
        ),
        migrations.AddField(
            model_name='fieldmodel',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_custom_form.FormModel'),
        ),
    ]
