# Generated by Django 2.1.2 on 2018-11-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '字段',
                'verbose_name_plural': '字段',
            },
        ),
    ]
