# Generated by Django 2.1.2 on 2018-11-09 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, unique=True)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '表单模型',
                'verbose_name_plural': '表单模型',
            },
        ),
        migrations.AddField(
            model_name='custommodel',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_form.FormModel'),
        ),
    ]
