# Generated by Django 2.1.2 on 2018-11-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_form', '0002_formmodel_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField(max_length=100)),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.AlterModelOptions(
            name='formmodel',
            options={'verbose_name': '表单模型', 'verbose_name_plural': '表单模型'},
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='field',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
