# Generated by Django 2.1.2 on 2018-11-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_form', '0003_auto_20181108_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommodel',
            name='age',
        ),
    ]
